### ISSUE TITLE
Sprite Collision issue

### ISSUE THREAD

**Issue by TFHFony** [ppeccin/WebMSX#60]
The new MSXDev'20 game Litter box doesn't run correctly on WebMSX. The error is related to this issue in OpenMSX:
https://github.com/openMSX/openMSX/issues/1198

When this issue was solved, this also solved the Litter Box (https://www.msxdev.org/2020/07/11/msxdev20-06-litter-box/) issue.

**Comment by TFHFony** [comment]
Additional information. Because of the bug, the ON SPRITE GOSUB routine gets called continiously which makes the game run very slow. Other effects: No sound eating the pils & you can catch the mouse before it's shown on screen.

**Comment by ppeccin** [comment]
This behavior was already corrected in release 6.0, wasn't it?

**Comment by TFHFony** [comment]
Yep, but probably not completely as the game still shows this behaviour in
WebMSX 6.0.



Op zo 12 jul. 2020 20:21 schreef ppeccin <notifications@github.com>:

> This behavior was already corrected in release 6.0, wasn't it?
>
>
>

**Comment by ppeccin** [comment]
Is it a MSX1 game?
Does it still show the problem running on a MSX1 machine on WebMSX?

**Comment by TFHFony** [comment]
Yes, it's an MSX 1 game and I'm running it in MSX1 mode on WebMSX in the
MSXDev section on my site:

https://www.file-hunter.com/MSXdev/index.php?id=litterbox

Op zo 12 jul. 2020 20:37 schreef ppeccin <notifications@github.com>:

> Is it a MSX1 game?
> Does it still show the problem running on a MSX1 machine on WebMSX?
>
>

**Comment by TFHFony** [comment]
OK... The issue seems to be solved by running it in MSX2 mode...
